import pandas as pd

# Create a Data Dictionary DataFrame
data_dict = pd.DataFrame({
    "Feature": [
        "uid", "originh", "originp", "responh", "responp", "flow_duration", 
        "fwd_pkts_tot", "bwd_pkts_tot", "fwd_data_pkts_tot", "bwd_data_pkts_tot", 
        "fwd_pkts_per_sec", "bwd_pkts_per_sec", "flow_pkts_per_sec", "down_up_ratio", 
        "fwd_header_size_tot", "fwd_header_size_min", "fwd_header_size_max", 
        "bwd_header_size_tot", "bwd_header_size_min", "bwd_header_size_max", 
        "flow_FIN_flag_count", "flow_SYN_flag_count", "flow_RST_flag_count", 
        "fwd_PSH_flag_count", "bwd_PSH_flag_count", "flow_ACK_flag_count", 
        "fwd_URG_flag_count", "bwd_URG_flag_count", "flow_CWR_flag_count", 
        "flow_ECE_flag_count", "fwd_pkts_payload.min", "fwd_pkts_payload.max", 
        "fwd_pkts_payload.tot", "fwd_pkts_payload.avg", "fwd_pkts_payload.std", 
        "bwd_pkts_payload.min", "bwd_pkts_payload.max", "bwd_pkts_payload.tot", 
        "bwd_pkts_payload.avg", "bwd_pkts_payload.std", "flow_pkts_payload.min", 
        "flow_pkts_payload.max", "flow_pkts_payload.tot", "flow_pkts_payload.avg", 
        "flow_pkts_payload.std", "fwd_iat.min", "fwd_iat.max", "fwd_iat.tot", 
        "fwd_iat.avg", "fwd_iat.std", "bwd_iat.min", "bwd_iat.max", "bwd_iat.tot", 
        "bwd_iat.avg", "bwd_iat.std", "flow_iat.min", "flow_iat.max", "flow_iat.tot", 
        "flow_iat.avg", "flow_iat.std", "payload_bytes_per_second", "fwd_subflow_pkts", 
        "bwd_subflow_pkts", "fwd_subflow_bytes", "bwd_subflow_bytes", "fwd_bulk_bytes", 
        "bwd_bulk_bytes", "fwd_bulk_packets", "bwd_bulk_packets", "fwd_bulk_rate", 
        "bwd_bulk_rate", "active.min", "active.max", "active.tot", "active.avg", 
        "active.std", "idle.min", "idle.max", "idle.tot", "idle.avg", "idle.std", 
        "fwd_init_window_size", "bwd_init_window_size", "fwd_last_window_size", 
        "bwd_last_window_size", "attack_category", "Label"
    ],
    "Description": [
        "Unique identifier for each network flow.", "Source host (IP address or hostname) initiating the connection.",
        "Source port used by the sender.", "Destination host (IP address or hostname) responding to the connection.", 
        "Destination port used by the receiver.", "Total duration of the network flow.", 
        "Total number of packets sent from the source to the destination.", 
        "Total number of packets sent from the destination to the source.", 
        "Total number of packets carrying data sent from the source.", 
        "Total number of packets carrying data sent from the destination.", 
        "Rate of packets sent per second from the source.", 
        "Rate of packets sent per second from the destination.", 
        "Overall rate of packets exchanged per second in the flow.", 
        "Ratio of downloaded packets to uploaded packets (bwd/fwd).", 
        "Total size of headers in forwarded packets.", 
        "Minimum header size in forwarded packets.", "Maximum header size in forwarded packets.", 
        "Total size of headers in backward packets.", "Minimum header size in backward packets.", 
        "Maximum header size in backward packets.", "Number of FIN (Finish) flags, indicating connection termination.", 
        "Number of SYN (Synchronization) flags, used to initiate TCP connections.", 
        "Number of RST (Reset) flags, used to reset connections.", 
        "Number of PSH (Push) flags in forwarded packets, indicating data should be pushed immediately.", 
        "Number of PSH (Push) flags in backward packets.", "Number of ACK (Acknowledgment) flags, used to confirm receipt of packets.", 
        "Number of URG (Urgent) flags in forwarded packets, indicating urgent data.", 
        "Number of URG (Urgent) flags in backward packets.", 
        "Number of CWR (Congestion Window Reduced) flags, related to TCP congestion control.", 
        "Number of ECE (Explicit Congestion Notification Echo) flags, indicating network congestion.", 
        "Minimum payload size in forwarded packets.", "Maximum payload size in forwarded packets.", 
        "Total payload size in forwarded packets.", "Average payload size in forwarded packets.", 
        "Standard deviation of payload size in forwarded packets.", "Minimum payload size in backward packets.", 
        "Maximum payload size in backward packets.", "Total payload size in backward packets.", 
        "Average payload size in backward packets.", "Standard deviation of payload size in backward packets.", 
        "Minimum payload size across all packets in the flow.", "Maximum payload size across all packets in the flow.", 
        "Total payload size across all packets in the flow.", "Average payload size across all packets in the flow.", 
        "Standard deviation of payload size across all packets in the flow.", 
        "Minimum inter-arrival time (IAT) between forwarded packets.", "Maximum inter-arrival time between forwarded packets.", 
        "Total inter-arrival time for forwarded packets.", "Average inter-arrival time for forwarded packets.", 
        "Standard deviation of inter-arrival time for forwarded packets.", "Minimum inter-arrival time between backward packets.", 
        "Maximum inter-arrival time between backward packets.", "Total inter-arrival time for backward packets.", 
        "Average inter-arrival time for backward packets.", "Standard deviation of inter-arrival time for backward packets.", 
        "Minimum inter-arrival time across all packets in the flow.", "Maximum inter-arrival time across all packets in the flow.", 
        "Total inter-arrival time across all packets in the flow.", "Average inter-arrival time across all packets in the flow.", 
        "Standard deviation of inter-arrival time across all packets in the flow.", 
        "Bytes of payload data transferred per second.", "Number of packets in the forward subflow.", 
        "Number of packets in the backward subflow.", "Number of bytes in the forward subflow.", 
        "Number of bytes in the backward subflow.", "Total bytes sent in bulk transfer mode (forward direction).", 
        "Total bytes received in bulk transfer mode (backward direction).", "Number of bulk packets sent (forward direction).", 
        "Number of bulk packets received (backward direction).", "Bulk transfer rate for forwarded packets.", 
        "Bulk transfer rate for backward packets.", "Minimum time a flow was active.", "Maximum time a flow was active.", 
        "Total time a flow was active.", "Average active time per session.", "Standard deviation of active time.", 
        "Minimum idle time (period of no packet exchange).", "Maximum idle time.", "Total idle time.", 
        "Average idle time per session.", "Standard deviation of idle time.", 
        "Initial TCP window size (forward direction).", "Initial TCP window size (backward direction).", 
        "Last observed TCP window size (forward).", "Last observed TCP window size (backward).", 
        "Type of attack (if applicable).", "Binary label (0 = benign, 1 = attack)."
    ]
})

# Save as CSV
data_dict_path = "data_description.csv"
data_dict.to_csv(data_dict_path, index=False)
